-- Migration: Widen CHECK constraints on orch_events and orchestrator_approvals
-- Task: task_1777388229341_541
-- Date: 2026-04-28
-- Author: dev (spec by codex — see orgs/revops-global/agents/codex/output/2026-04-28-schema-constraint-migration.md)
--
-- Context: A1 Phase 1-3 discovered two CHECK constraints too narrow for the bus event
-- vocabulary. This migration removes the constraint on orch_events.event_type entirely
-- (values are generated by trusted internal code, not user input) and replaces the
-- constraint on orchestrator_approvals.action_type with the full ApprovalCategory enum.
--
-- Execution: Run in Supabase SQL Editor. PostgREST RPC cannot execute DDL.
-- Run Migration 1 before Migration 2 (independent, but this order is safer).

-- ============================================================
-- Migration 1: Drop CHECK constraint on orch_events.event_type
-- ============================================================
-- Current whitelist was: agent_message, telegram_inbound, telegram_outbound,
-- task_created, task_completed, task_blocked (too narrow for bus event vocabulary).
-- Recommendation: drop entirely — values are internal, a stable whitelist can
-- be re-added once the full bus event vocabulary is finalised.

DO $$
DECLARE
  cname text;
BEGIN
  SELECT conname INTO cname
  FROM pg_catalog.pg_constraint
  WHERE conrelid = 'orch_events'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%event_type%';

  IF cname IS NOT NULL THEN
    EXECUTE 'ALTER TABLE orch_events DROP CONSTRAINT ' || quote_ident(cname);
    RAISE NOTICE 'Dropped orch_events constraint: %', cname;
  ELSE
    RAISE NOTICE 'No event_type constraint on orch_events — nothing to drop';
  END IF;
END $$;

-- Fallback (use if pg_catalog not accessible in your Supabase context):
-- ALTER TABLE orch_events DROP CONSTRAINT IF EXISTS orch_events_event_type_check;


-- ============================================================
-- Migration 2: Replace CHECK constraint on orchestrator_approvals.action_type
-- ============================================================
-- All probed action_type values were rejected (constraint definition unknown via
-- PostgREST). Drop existing constraint and replace with ApprovalCategory values
-- from src/types/index.ts.

-- Step 1: drop existing action_type constraint
DO $$
DECLARE
  cname text;
BEGIN
  SELECT conname INTO cname
  FROM pg_catalog.pg_constraint
  WHERE conrelid = 'orchestrator_approvals'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%action_type%';

  IF cname IS NOT NULL THEN
    EXECUTE 'ALTER TABLE orchestrator_approvals DROP CONSTRAINT ' || quote_ident(cname);
    RAISE NOTICE 'Dropped orchestrator_approvals action_type constraint: %', cname;
  ELSE
    RAISE NOTICE 'No action_type constraint on orchestrator_approvals — nothing to drop';
  END IF;
END $$;

-- Fallback:
-- ALTER TABLE orchestrator_approvals DROP CONSTRAINT IF EXISTS orchestrator_approvals_action_type_check;

-- Step 2: add constraint matching ApprovalCategory (src/types/index.ts)
ALTER TABLE orchestrator_approvals
  ADD CONSTRAINT orchestrator_approvals_action_type_check
  CHECK (action_type IN (
    'external-comms',
    'financial',
    'deployment',
    'data-deletion',
    'other'
  ));


-- ============================================================
-- Migration 3: Ensure orchestrator_approvals.status constraint matches ApprovalStatus
-- ============================================================
-- ApprovalStatus = 'pending' | 'approved' | 'rejected' (src/types/index.ts)
-- Drop and re-add if existing constraint rejects these values.

DO $$
DECLARE
  cname text;
BEGIN
  SELECT conname INTO cname
  FROM pg_catalog.pg_constraint
  WHERE conrelid = 'orchestrator_approvals'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%status%';

  IF cname IS NOT NULL THEN
    EXECUTE 'ALTER TABLE orchestrator_approvals DROP CONSTRAINT ' || quote_ident(cname);
    RAISE NOTICE 'Dropped orchestrator_approvals status constraint: %', cname;
  ELSE
    RAISE NOTICE 'No status constraint on orchestrator_approvals — skipping drop';
  END IF;
END $$;

ALTER TABLE orchestrator_approvals
  ADD CONSTRAINT orchestrator_approvals_status_check
  CHECK (status IN ('pending', 'approved', 'rejected'));


-- ============================================================
-- Post-migration validation queries (run to verify, then rollback test rows)
-- ============================================================

-- Verify orch_events accepts new event types:
-- INSERT INTO orch_events (org_id, event_type, agent_id, message, metadata)
-- VALUES ('00000000-0000-0000-0000-000000000001', 'heartbeat/agent_heartbeat', 'dev', 'migration test', '{}')
-- ON CONFLICT DO NOTHING;

-- Verify orchestrator_approvals accepts ApprovalCategory values:
-- INSERT INTO orchestrator_approvals (action_type, status)
-- VALUES ('external-comms', 'pending')
-- ON CONFLICT DO NOTHING;
-- DELETE FROM orchestrator_approvals WHERE action_type = 'external-comms' AND message IS NULL;
